using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DatabaseConsole
{
    class Program
    {
        static void Main(string[] args)
        {

            #region Demonstrate Code First automatically generated by entity from an existing DB

            Console.WriteLine("****** Code First generated by entity based on DB being there first ******");

            // Remove the original DB & Create a new one using the other Model, to prove that the
            // code first generates the database correctly
            DatabaseHandler.DeleteDB();
            DatabaseHandler.CreateDB();

            DatabaseHandler.GetDataByApplications();
            DatabaseHandler.GetDataByUsers();
            Console.ReadLine();
            DatabaseHandler.InsertADummyUser();
            Console.ReadLine();
            DatabaseHandler.DeleteADummyUser();

            #endregion

            Console.ReadLine();
        }
    }
}
